export const CODE_BLOCK_CLASS = "cb";

export const LINE_CLASS = `${CODE_BLOCK_CLASS}-l`;
export const LINE_NUMBER_CLASS = `${CODE_BLOCK_CLASS}-n`;

export const LINE_NUMBERS_CLASS = `${CODE_BLOCK_CLASS}-ln`;
export const LINE_NUMBERS_SHOW_CLASS = `${LINE_NUMBERS_CLASS}-s`;

export const SECTION_CONTENT_CLASS = `${CODE_BLOCK_CLASS}-sc`;
export const SECTION_CONTENT_INDENT_CLASS = `${SECTION_CONTENT_CLASS}-i`;

export const SECTION_CONTEXT_CLASS = `${CODE_BLOCK_CLASS}-sx`;
export const SECTION_CONTEXT_AFTER_CLASS = `${SECTION_CONTEXT_CLASS}-a`;
export const SECTION_CONTEXT_BEFORE_CLASS = `${SECTION_CONTEXT_CLASS}-b`;

export const SECTION_EXPANDED_CLASS = `${CODE_BLOCK_CLASS}-se`;

export const SECTION_EXPANDER_CLASS = `${CODE_BLOCK_CLASS}-sh`;
export const SECTION_EXPANDER_AFTER_CLASS = `${SECTION_EXPANDER_CLASS}-a`;
export const SECTION_EXPANDER_BEFORE_CLASS = `${SECTION_EXPANDER_CLASS}-b`;
export const SECTION_EXPANDER_HIDE_CLASS = `${SECTION_EXPANDER_CLASS}-h`;
export const SECTION_EXPANDER_SHOW_CLASS = `${SECTION_EXPANDER_CLASS}-s`;

export const SPACE_CLASS = `${CODE_BLOCK_CLASS}-s`;
export const TAB_CLASS = `${CODE_BLOCK_CLASS}-t`;

export const KEY_CLASS = `${CODE_BLOCK_CLASS}-k`;
